// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izfrkbrlwmretkzjwydu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6ZnJrYnJsd21yZXRremp3eWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjQ1OTUsImV4cCI6MjA1OTg0MDU5NX0.Wp_aL2JnWfvuY4byH819HGlfy4tRbImvbF65uDYREoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);